name: Dart CI

on:
  push:
    branches:
      - main  # Run CI on pushes to main
  pull_request:
    branches:
      - main  # Run CI on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable  # Use the latest stable Dart SDK

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Run linter
        run: dart analyze
